apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alfresco-volume-claim
  namespace: alfresco
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: efs-sc
