apiVersion: batch/v1
kind: Job
metadata:
  name: alfresco-dir-creator
  namespace: alfresco 
spec:
  template:
    spec:
      containers:
      - name: alfresco-dir-creator
        image: busybox
        command: ["/bin/sh"]
        args: ["-c", "mkdir -p --mode=770 /shared/alfresco-content-services/filestore-data /shared/alfresco-content-services/repository-data /shared/alfresco-infrastructure/activemq-data&&chown -R 33000:1000 /shared/alfresco-content-services&&chown -R 33031:1000 /shared/alfresco-infrastructure&&chmod -R 770 /shared&&echo Alfresco Directory creation -- DONE"]
        volumeMounts:
        - name: efs-pvc
          mountPath: /shared
      volumes:
      - name: efs-pvc
        persistentVolumeClaim:
          claimName: alfresco-volume-claim
      restartPolicy: Never
  backoffLimit: 5
