apiVersion: batch/v1
kind: Job
metadata:
  name: alfresco-dir-creator
  namespace: alfresco 
spec:
  template:
    spec:
      containers:
      - name: alfresco-dir-creator
        image: busybox
        command: ["/bin/sh"]
        args: ["-c", "mkdir -p --mode=760 /shared/alfresco-content-services/filestore-data /shared/alfresco-content-services/repository-data&&chown -R 33000:1000 /shared/alfresco-content-services"]
        volumeMounts:
        - name: efs-pvc
          mountPath: /shared
      volumes:
      - name: efs-pvc
        persistentVolumeClaim:
          claimName: alfresco-volume-claim
      restartPolicy: Never
  backoffLimit: 5
