apiVersion: v1
kind: PersistentVolume
metadata:
  name: alfresco-pv
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: <ReplaceWithEFSFileSystemId>
